### ISSUE TITLE
Offer installation via addon-store

### ISSUE THREAD

**Issue by membersound** [erikarenhill/solaredge-modbus-hass#11]
It would be great if this module could be installed by simply adding the repository to the HA addon store. Lot's community addons provide this feature.

Or maybe through the HACs addon.

**Comment by erikarenhill** [comment]
need more docs, but hacs.json is added so it's possible to install it through hacs

**Comment by membersound** [comment]
I tried adding `https://github.com/erikarenhill/solaredge-modbus-hass/` as custom repository. Unfortunately the repository is not accepted. But I also don't get an error message or any error logs. Strange.

**Comment by membersound** [comment]
Great, it worked!
