### ISSUE TITLE
homeassitant version 2021.6 now requires a version key

### ISSUE THREAD

**Issue by mkrasselt1** [erikarenhill/solaredge-modbus-hass#32]
https://www.home-assistant.io/blog/2021/06/02/release-20216/#new-integrations

Add a Version key to manifest file and please merge my pull request if possible, i would like to maintain this repos as well, add official support and soon :)

**Comment by rickroetenberg** [comment]
yes please

**Comment by erikarenhill** [comment]
the manifest have had a version since about april; https://github.com/erikarenhill/solaredge-modbus-hass/commit/cfa264d274d871138a11b68325e33d54e0e6348c#diff-508b98b447c75e18020d3e5f3d570c95f2d943886e2ac054a823095e76b0961f
