### ISSUE TITLE
Please, a bit of help installing component

### ISSUE THREAD

**Issue by ctrl-alt-d** [erikarenhill/solaredge-modbus-hass#37]
I followed "manual install" of **[How to install](https://github.com/erikarenhill/solaredge-modbus-hass#how-to-install)** (copy into folder):

![Selecció_310](https://user-images.githubusercontent.com/3105983/132249494-5365247f-7cdc-4714-b08e-d3c8ce891439.png)

What is the next step?

I tried to add integration via `/config/integrations` but I'm unable to locate this component:

![Selecció_311](https://user-images.githubusercontent.com/3105983/132249613-91cf8062-5bd7-4fba-ab6f-f193940d8207.png)

(Also I tried to restart HA)

Sorry about this noob question.

**Comment by ternzer** [comment]
same issue. Repo install/restart HA. Solaredge Modbus is not listed in Configuration>Integrations. Tested another integration just to be safe. Also reinstalled this repo.

**Comment by seanw18** [comment]
same same

**Comment by borgswen** [comment]
Hi, This component shoud be set up trough yaml code. It's sort of complicated but there are helpfull guides out there.

**Comment by erikarenhill** [comment]
Hello,

You have to follow the examples by looking here:
https://github.com/erikarenhill/solaredge-modbus-hass/blob/master/sample-configuration.yaml

It is not configurable through the UI yet.
The first 7 rows is the most important to set up communication with the inverter such as IP and port.
