### ISSUE TITLE
Add to integration and how check entieties

### ISSUE THREAD

**Issue by pepsonEL** [erikarenhill/solaredge-modbus-hass#38]
Hi. Is any chance to rebuild this integration to after install by HACS we can configure it from Configuration>Integration and add integration button ? No by edit configuration.yaml....

How i can verify what entieties are from this integration ?

**Comment by erikarenhill** [comment]
Currently it's not possible to add the integration through the UI

This component exposes one sensor called SolarEdge Modbus with multiple attributes.
See the sample-configuration here: https://github.com/erikarenhill/solaredge-modbus-hass/blob/master/sample-configuration.yaml
 for how to pick specific attributes with template sensors.

![image](https://user-images.githubusercontent.com/758402/145978690-283698e3-d044-457f-82e7-51bcd990b097.png)

I will look into adding support for config through the UI
