### ISSUE TITLE
SolarEdgeModbusSensor  implements device_state_attributes.

### ISSUE THREAD

**Issue by godfreym29** [erikarenhill/solaredge-modbus-hass#43]
Running HAOS - core-2022.2.3 on a raspberry Pi 4 with4GB mem & ssd hd
running the latest version of solaredge-modbus-hass which was installed using HACS
The intergration is returnong data each time it runs and connects to the inverter.

I get these errors in the HA log:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:574
First occurred: 15:30:51 (2 occurrences)
Last logged: 15:30:51

Entity sensor.solaredge_modbus (<class 'custom_components.solaredge_modbus.sensor.SolarEdgeModbusSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.solaredge_modbus_meter_1 (<class 'custom_components.solaredge_modbus.sensor.SolarEdgeMeterSensor'>) implements device_state_attributes. Please report it to the custom component author.

These are followed later by this error (which may or may not be related):

Logger: homeassistant.util.async_
Source: util/async_.py:144
First occurred: 15:30:51 (2279 occurrences)
Last logged: 17:09:48

Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for solaredge_modbus doing blocking calls at custom_components/solaredge_modbus/sensor.py, line 75: sleep(0.005)
Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for solaredge_modbus doing blocking calls at custom_components/solaredge_modbus/sensor.py, line 277: sleep(0.005)

**Comment by erikarenhill** [comment]
resolved with new version yesterday
